#!/usr/bin/env python

import os
import methods

Import('env')
Import('env_modules')

env_hololens_ar = env_modules.Clone()

env_hololens_ar.add_source_files(env.modules_sources, '*.cpp')

#SConscript("shaders/SCsub")
