#!/usr/bin/env python

Import('env')
Import('env_modules')

# Thirdparty source files

env_pjsip = env_modules.Clone()

if (env['builtin_pjsip'] != 'no'):
	thirdparty_dir = "#thirdparty/"
	thirdparty_sources = [
	"pjsip/src/pjsua2/types.cpp",
	"pjsip/src/pjsua2/account.cpp",
	"pjsip/src/pjsua2/call.cpp",
	"pjsip/src/pjsua2/json.cpp",
	"pjsip/src/pjsua2/media.cpp",
	"pjsip/src/pjsua2/persistent.cpp",
	"pjsip/src/pjsua2/presence.cpp",
	"pjsip/src/pjsua2/siptypes.cpp",
    ]
	thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

	env_pjsip.add_source_files(env.modules_sources, thirdparty_sources)
	env_pjsip.Append(CPPPATH=[thirdparty_dir + "/pjsip", thirdparty_dir + "/pjsip/include"])
	env_pjsip.Append(CPPPATH=[thirdparty_dir + "/pjlib", thirdparty_dir + "/pjlib/include"])
	env_pjsip.Append(CPPPATH=[thirdparty_dir + "/pjlib-util", thirdparty_dir + "/pjlib-util/include"])
	env_pjsip.Append(CPPPATH=[thirdparty_dir + "/pjmedia", thirdparty_dir + "/pjmedia/include"])
	env_pjsip.Append(CPPPATH=[thirdparty_dir + "/pjnath", thirdparty_dir + "/pjnath/include"])
	env_pjsip.Append(CPPFLAGS=["-DGODOT_ENET"])

#env_pjsip.add_source_files(env.modules_sources, "*.cpp")
